version: "3.9"

networks:
  traefik-proxy-network:
    external: true # 使用已存在、组合（compose 文件）之外的 network，如果不存在则提示 network proxy-net declared as external, but could not be found
    name: proxy-net # 指定名称

services:
  jike-nuxt:
    restart: always
    image: jike-nuxt
    container_name: jike-nuxt-container
    volumes:
      - ./files/:/code/files/
    build:
      context: .
    networks: # 指定 network 使这个容器成为该网络的一部分
      - traefik-proxy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.jike-nuxt.rule=PathPrefix(`/jike`)


  jike-nginx:
    restart: always
    image: brotli:latest
    container_name: jike-nginx-container
    volumes:
      - ./files/:/usr/share/nginx/html/files/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks: # 指定 network 使这个容器成为该网络的一部分
      - traefik-proxy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.jike-nginx.rule=PathPrefix(`/files`)

